# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:

    Python312:
      python.version: '3.12'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt --upgrade
  displayName: 'Install dependencies'

- script: |
    echo "Current Working Directory: $(pwd)"
    PA_TOKEN=$(PA_TOKEN) \
    ACCOUNT_NAME=$(ACCOUNT_NAME) \
    ACCOUNT_KEY=$(ACCOUNT_KEY) \
    python Agilidade_Dados/src/main.py
    echo "Contents of Directory After Script Execution: $(ls -al)"
  displayName: 'Executando script'

